"""
Django settings for rubion project.

Generated by 'django-admin startproject' using Django 1.11.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

from __future__ import absolute_import, unicode_literals

# Build paths inside the project like this: os.path.join(BASE_DIR, ...
import os
from django.utils.translation import ugettext_lazy as _

PROJECT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BASE_DIR = os.path.dirname(PROJECT_DIR)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/


# Application definition

INSTALLED_APPS = [
    'rubion',
    'ugc',
    'userinput',
    'userdata',
    'search',
    'website',
    'notifications',
    'instruments',
    'courses',

    'rubauth',


    'wagtail.contrib.modeladmin',
    'wagtail.contrib.table_block',
    'wagtail.contrib.routable_page',
    'wagtailfontawesome',
    'wagtail.contrib.settings',

    'wagtail.contrib.styleguide',    

    'wagtail.contrib.forms',
    'wagtail.contrib.redirects',
    'wagtail.embeds',
    'wagtail.sites',
    'wagtail.users',
    'wagtail.snippets',
    'wagtail.documents',
    'wagtail.images',
    'wagtail.search',
    'wagtail.admin',
    'wagtail.core',


#    'wagtail_modeltranslation', 
    'modelcluster',
    'taggit',
#    'dashboard',


    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rubionadmin'

]

MIDDLEWARE = [
    'django.contrib.sessions.middleware.SessionMiddleware',

    'django.middleware.locale.LocaleMiddleware',

    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
#    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',

    'wagtail.core.middleware.SiteMiddleware',
    'wagtail.contrib.redirects.middleware.RedirectMiddleware',
]

ROOT_URLCONF = 'rubion.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(PROJECT_DIR, 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'wagtail.contrib.settings.context_processors.settings',
            ],
        },
    },
]

WSGI_APPLICATION = 'rubion.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'rubion2',
    }
}

# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGES = (
    ( 'en', _('English') ),
    ( 'de', _('German') ),
)
LANGUAGE_CODE = 'en'


TIME_ZONE = 'Europe/Berlin'

USE_I18N = True

USE_L10N = True

USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
]

STATICFILES_DIRS = [
    os.path.join(PROJECT_DIR, 'static'),
]

STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATIC_URL = '/static/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

INVOICE_ROOT = os.path.join(MEDIA_ROOT, 'invoices')
# Wagtail settings

WAGTAIL_SITE_NAME = "rubion"

# Base URL to use when referring to full URLs within the Wagtail admin backend -
# e.g. in notification emails. Don't include '/admin' or a trailing slash
BASE_URL = 'http://example.com'

WAGTAILADMIN_RICH_TEXT_EDITORS = {
    'basic': {
        'WIDGET': 'rubion.customizable_rich_text.CustomizableHalloRichTextArea',
        'OPTIONS': [
            'halloformat', 'halloreundo', 'hallolists', 'hallowagtaillink', 'hallorequireparagraphs'
        ]
    },
    'simple': {
        'WIDGET': 'rubion.customizable_rich_text.CustomizableHalloRichTextArea',
        'OPTIONS': [
            'halloformat', 'halloreundo', 'hallowagtaillink', 'hallorequireparagraphs'
        ]
    },
    'default': {
        'WIDGET': 'wagtail.admin.rich_text.HalloRichTextArea',
    }
}
AUTHENTICATION_BACKENDS = (
    'rubauth.auth.LDAPBackend',
    'django.contrib.auth.backends.ModelBackend',
)

RUB_LDAP_SERVER = 'ldap.ruhr-uni-bochum.de'


#conn.rebind(user='uid=happepbo,', password="<pwd>")

ALLOWED_HOSTS = [
    'test.rubion.rub.de',
    'www.rubion.rub.de',
    'localhost',
]
WAGTAIL_FRONTEND_LOGIN_TEMPLATE = 'rubauth/login.html'
LOGIN_URL = '/login/'


RUBION_MAIL_FROM = 'RUBION <rubion-automatic-mail@ruhr-uni-bochum.de>'


ADMINS = [('Patrick', 'patrick.happel@rub.de'),]
LOCALE_PATHS = (
    os.path.join(BASE_DIR, 'locale'),
)
PASSWORD_REQUIRED_TEMPLATE = 'website/password_required.html'
